version: '3'
services:
  subconv:
    image: wouisb/subconv:latest
    container_name: subconv
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
